# Generated by Django 3.2.9 on 2022-05-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=100)),
                ('onair', models.BooleanField(default=True)),
                ('takeofftime', models.DateTimeField()),
                ('beforenext_takeoff', models.TimeField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
