# Generated by Django 3.2.9 on 2022-05-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_alter_plane_takeofftime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='beforenext_takeoff',
            field=models.IntegerField(),
        ),
    ]
