name: cloudrun-deploy-producion

on:
    push:
        branches:
            - main

jobs:
    build:
        name: 'Cloud Run Producion Deplyoment'
        runs-on: ubuntu-latest
        steps:
           - name: 'Checkout'
             uses: actions/checkout@master

           - name: 'Setup GCP Service Account'
             id: auth
             uses: google-github-actions/auth@v1
             with:
                credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_SECRET }}
            
           - name: 'Configure Docker'
             run: make gcloud-docker-init
           
           - name: 'Build'
             env:
                GCP_PROJECT_ID: ${{ secrets.GCP_PROCEJT_ID }}
                ENVIROMENT: 'production'
             run: make gcloud-docker-build

           - name: 'Push'
             env:
                GCP_PROJECT_ID: ${{ secrets.GCP_PROCEJT_ID }}
                ENVIROMENT: 'production'
             run: make gcloud-docker-push

           - name: 'Deploy'
             env:
                GCP_PROJECT_ID: ${{ secrets.GCP_PROCEJT_ID }}
                ENVIROMENT: 'production'
             run: make gcloud-docker-deploy