name: cloudrun-deploy-producion

on:
    push:
        branches:
            - main

jobs:
    build:
        name: 'Cloud Run Producion Deplyoment'
        runs-on: ubuntu-latest
        steps:
           - name: 'Checkout'
             uses: actions/checkout@master

           - name: 'Setup GCP Service Account'
             uses: google-github-actions/setup-gcloud@master
             with:
                procejt_id: ${{ secrets.GCP_PROCET_ID }}
                service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_SECRET }}
                export_deault_credentials: true
            
           - name: 'Configure Docker'
             run: make gcloud-docker-init
           
           - name: 'Build'
             env:
                GCP_PROJECT_ID: ${{ secrets.GCP_PROCET_ID }}
                ENVIROMENT: 'production'
             run: make gcloud-docker-build

           - name: 'Push'
             env:
                GCP_PROJECT_ID: ${{ secrets.GCP_PROCET_ID }}
                ENVIROMENT: 'production'
             run: make gcloud-docker-push

           - name: 'Deploy'
             env:
                GCP_PROJECT_ID: ${{ secrets.GCP_PROCET_ID }}
                ENVIROMENT: 'production'
             run: make gcloud-docker-deploy